(function(z){
z.Qs=function(a){var b=z.ka(a);return function(){var c=this||z.m,c=c.closure_memoize_cache_||(c.closure_memoize_cache_={}),d;d=arguments;for(var f=[b],g=d.length-1;0<=g;--g)f.push(typeof d[g],d[g]);d=f.join("\x0B");return c.hasOwnProperty(d)?c[d]:c[d]=a.apply(this,arguments)}};var Rs=function(){z.S.call(this)};
var Ss=function(){function a(){(0,window.$)(this).trigger("requestStory")}function b(){var a=f.filter(".current");a.length&&d.css("top",a.position().top+a.height()/2-10)}var c={member:z.Qs(function(a){return window.$.get("/node/HomeHeroStoryV2",{params:{member_hash:a}})}),topic:z.Qs(function(a){return window.$.get("/node/HomeTopicStoryV2",{params:{url_token:a}})})},d=(0,window.$)("div.single-story \x3e .icon-sign").addClass("visible"),f=(0,window.$)("a.rep"),g=null;f.mouseenter(function(){g=(0,window.setTimeout)((0,z.t)(a,
this),500)}).mouseleave(function(){(0,window.clearTimeout)(g)}).click(a).on("requestStory",function(){var a=(0,window.$)(this),f=a.data(),g=f.type,f=f.token;a.addClass("current").siblings().removeClass("current");b();c[g](f).done(function(b){(0,window.$)(".single-story-inner").fadeOut(150,function(){(0,window.$)(this).remove();(0,window.$)(b).insertAfter(d).hide().fadeIn(150)});a.trigger("afterRequestStory")})});b()};
var Ts=function(){function a(){(0,window.clearInterval)(g);g=null}function b(){g||(g=(0,window.setInterval)(function(){(0,window.$)(c()).trigger("requestStory")},5E3))}function c(){var a=f.filter(":not(.current)").get();z.B.wR(a);return a[0]}var d=(0,window.$)("div.single-story"),f=(0,window.$)("div.rep"),g=null;d.hover(a,b);f.on("requestStory",a).on("afterRequestStory",b);return{start:b,stop:a}};
var Us=function(a){function b(){c.hide();d.show()}var c=(0,window.$)("div.mobi-front"),d=(0,window.$)("div.desk-front");c.find(".js-signin, .js-signup").click(function(){d.find(".js-title-label").text("\u8fd4\u56de");d.find(".return").off().click(function(){window.location.hash=""});b()});a.o().g(window,"hashchange",function(){var a=window.location.hash.slice(1);"signin"===a?(b(),g.st()):"signup"===a?(b(),g.lH()):(d.css("display",""),c.css("display",""))});a.o().g(z.X,["accountcallback","sina_callback",
"qqconn_callback"],b);a=window.location.hash.slice(1);var f="signin"===a||"signup"!==a&&(0,window.$)("div.view-signin").hasClass("selected"),g=new z.Rk;"signin"!==a&&"signup"!==a||b();g.Hc=!0;g.gn=f?"signin":"signup";g.w(z.y("js-sign-flow"))};z.v(Rs,z.S);Rs.prototype.init=function(){this.w(window.document.body)};Rs.prototype.D=function(a){Rs.v.D.call(this,a);Ss();Us(this);this.Ln();z.ah||(a=Ts(),a.start(),z.Fc(this,a.stop))};
Rs.prototype.Ln=function(){window.$.each({".app-link.ios":["click_zhihu_ios_dl_link","homepage_not_logged_in"],".app-link.android":["click_zhihu_android_dl_link","homepage_not_logged_in"],'a.app-download-button[href^\x3d"http://itunes"]':["click_zhihu_ios_dl_link","homepage_mobile_big_not_logged_in"],'a.app-download-button[href^\x3d"https://play.google.com"]':["click_zhihu_android_dl_link","homepage_mobile_big_not_logged_in"]},function(a,b){(0,window.$)(a).on("click",function(){z.Y.apply(null,["app-promotion"].concat(b))})})};
z.ua("ZH.entrySignPage",function(){(new Rs).init()});z.jf("sign");}).call(this, __z_z__);
//@ sourceURL=module_sign.js